# CONFIGURAÇÕES - Spring WebFlux + SQLite
spring.application.name=API-RESTFUL-WEB-FORNECEDORES-SPRINGJDBC-WEBFLUX

# BANCO DE DADOS SQLITE
spring.datasource.url=jdbc:sqlite:fornecedores.DB
spring.datasource.driver-class-name=org.sqlite.JDBC

# Inicializar schema.sql automaticamente
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Porta do servidor (Netty)
server.port=8080