CREATE TABLE IF NOT EXISTS FORNECEDORES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    RAZAOSOCIALFORNECEDOR TEXT NOT NULL,
    CNPJFORNECEDOR TEXT NOT NULL,
    ENDERECO TEXT NOT NULL,
    BAIRRO TEXT NOT NULL,
    MUNICIPIO TEXT NOT NULL,
    CEP TEXT NOT NULL
);
